### ISSUE TITLE
Keybindings do not work

### ISSUE THREAD

**Issue by pmatulis** [ryanmsnyder/telescope-toggleterm.nvim#4]
`<CR>` does not open a terminal. Instead, it selects the first terminal. `<C-i>` and `<C-d>` creates and deletes a terminal however. I just can't open any terminal.

I noticed that `<C-d>` will not delete all terminals in one Telescope session. I need to close the session and re-open it. The last remaining terminal is especially tenacious. It's weird.

**Comment by ryanmsnyder** [comment]
Hi @pmatulis, can you share your `toggleterm-manager` config with me?

**Comment by pmatulis** [comment]
I updated my initial comment as there were formatting problems and the description was not complete.

Configuration:

```
local toggleterm_manager = require("toggleterm-manager")
local actions = toggleterm_manager.actions

require("toggleterm-manager").setup {
  mappings = {
    i = {
      ["<CR>"]  = { action = actions.toggle_term, exit_on_action = false }, -- toggles terminal open/closed
      ["<C-i>"] = { action = actions.create_term, exit_on_action = false }, -- creates a new terminal buffer
      ["<C-d>"] = { action = actions.delete_term, exit_on_action = false }, -- deletes a terminal buffer
      ["<C-r>"] = { action = actions.rename_term, exit_on_action = false }, -- provides a prompt to rename a terminal
    },
  },
  titles = {
    preview = "Preview",
    prompt = " Terminals",
    results = "Results"
  },
}

```

**Comment by ryanmsnyder** [comment]
Thanks for providing the config. I just tested it on a clean install of NeoVim and it worked as expected for me. Also, just a note - your current config contains defaults of `toggleterm-manager` so you can actually get away with just calling:

```lua
local toggleterm_manager = require("toggleterm-manager")
toggleterm_manager.setup {}
```

Anyway, can you provide the current commit of `toggleterm-manager` that you have installed? Can you also provide your `toggleterm` config?

**Comment by pmatulis** [comment]
I do not know how to get the commit (would be nice to know) but I just updated with `:PlugUpdate` and the behaviour remains.

Its configuration is:

```
require("toggleterm").setup {
  open_mapping = [[<c-\>]],
  direction = 'float',
  float_opts = {
    border = 'curved',
    width = 125,
    height = 25,
  },
  highlights = {
    FloatBorder = {
      guifg = "#C39CC3",
      guibg = "#191616",
    },
  },
}
```

**Comment by ryanmsnyder** [comment]
Hi @pmatulis, I apologize for the late response. Please let me know if you're still having this issue.

**Comment by meetmangukiya** [comment]
`<CR>` doesnt work for me either, it works if you have `exit_on_action=true`
